### PR TITLE
Enable live filtering of results, making a Filter button unnecessary.

### PR DESCRIPTION
**Pull request by joshuak94**
Additionally, moved the link into the tournament name, getting rid of the "Join" column. I think this makes it overall a bit cleaner. Less buttons to have to press, less content on the screen.

### CODE REVIEW

**Comment by joshuak94** [comment]
Also, I think it would be useful for visibility if we create a separate topic on the Lichess forums (and also on reddit?). Would you mind if I posted a link on the chess subreddit?

**Comment by serbathome** [comment]
I'll check later in the evening.

On the filtering/ search form, it is very difficult to keep it clean and
reach at the same time.
I'm thinking about adding hidden forms with toggle buttons. Default page
will just show the table and a simple filtering field, so that once you
select, the table sorts automatically. And we can add a button, like
advanced search, which if clicked will open up the whole menu with all
possible options and search field.

Another thing is - we are limited to what public API is exposing and it is
clearly not everything. We can either talk to core dev team and ask them to
expose more, probably with tighter rate control or can just try to
implement ourselves and make a pull/merge request for the master branch of
lila repo.

What do you think?

Regards,
Sergey

**Comment by joshuak94** [comment]
Hmmm I'm not sure what you mean by "keep it clean and reach at the same time". But, I do agree that a hidden "advanced search" would be very nice, because there are many other options one could filter by (for example, only looking for games which are <1500).

Yeah, the public API is a bit weird with what is actually provided on tournaments. For example, it's weird that they provide a boolean for whether the rating is capped, but don't provide the actual rating cap and force parsing of the title.

I'm not sure the best way to proceed on that front. I guess talking to the core dev team would be nicer, I would have no clue on how to work on the lila repo.

**Comment by joshuak94** [comment]
But then with the "simple search & advanced search" scheme, I think the simple search should just be a search bar, a search icon button, and then a clear button.

**Comment by joshuak94** [comment]
@serbathome I've pushed a new commit which creates an "Advanced" button and moved the status and variant filters there.

I think a simple search having just a search bar is more intuitive, as that's how most websites have their simple searches set up.

**Comment by serbathome** [comment]
Agree, we could like google, simple search field in the middle with reset
button

[image: image.png]

Regards,
Sergey

**Comment by joshuak94** [comment]
Hmmm I'm not seeing the image. But regardless, that's what I did in the last commit. However, I can't get the search field to expand to full width correctly...

**Pull request merged**
